name: Run Python Script

on: [push]

jobs:
  run-python-script:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run hello.py
        run: python hello.py
